### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_72" referenced by "/data/app/com.example.javaswift-90fyPKGjL7uwdUwOrcdYNA==/base.apk!/lib/arm64-v8a/libFoundation.so"...

### ISSUE THREAD

**Issue by XiyaoXirui** [buttaface/swift-android-sdk#101]
Hi buttaface,

When i use this sdk in my Android project, I got this error about libFoundation.so. 
Do you know why this happens? thanks a lot:

FATAL EXCEPTION: main
                                                                                                    Process: com.example.javaswift, PID: 6003
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "UCNV_FROM_U_CALLBACK_STOP_72" referenced by "/data/app/com.example.javaswift-90fyPKGjL7uwdUwOrcdYNA==/base.apk!/lib/arm64-v8a/libFoundation.so"...
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1667)
                                                                                                    	at com.example.javaswift.MainActivity.loadNativeDependencies(MainActivity.kt:31)
                                                                                                    	at com.example.javaswift.MainActivity.onCreate(MainActivity.kt:12)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7815)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7804)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7697)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by buttaface** [comment]
To use these Swift libraries in an app, you will need to put them all in one directory like `lib/arm64-v8a/` and set their runpaths to find each other, ie `$ORIGIN` if they are all in the same directory.

This error is usually because libicu is not referenced by Foundation in such a way. Have you set that up?

**Comment by buttaface** [comment]
[Could also be related to this issue brought up last year](https://github.com/buttaface/swift-android-sdk/issues/53#issuecomment-1169785181), I have not tried Swift in an Android app yet, only as executables on the command line, so not too familiar with those dynamic linking issues.

**Comment by buttaface** [comment]
Closing since no response, let us know if you got it to work.
